In [2]:
import numpy as np

W = 6

ws = [2, 2, 3, 5]
cs = [6, 5, 6, 9]

n = len(ws)

C = np.zeros((W + 1, n + 1))

for w in range(1, W + 1):
    for k in range(1, n + 1):
        C[w, k] = C[w, k - 1]
        
        if (ws[k - 1] <= w):
            C[w, k] = max(C[w - ws[k - 1], k - 1] + cs[k - 1], C[w, k - 1])

print(C)

[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  6.  6.  6.  6.]
 [ 0.  6.  6.  6.  6.]
 [ 0.  6. 11. 11. 11.]
 [ 0.  6. 11. 12. 12.]
 [ 0.  6. 11. 12. 12.]]
